"""Migración inicial con base de datos actualizada

Revision ID: b86930486e7d
Revises: 
Create Date: 2024-12-12 04:25:21.860687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b86930486e7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amigo')
    op.drop_table('mensaje')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.drop_column('descripcion')
        batch_op.drop_column('provider')
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('banner_imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_imagen', mysql.VARCHAR(length=255), server_default=sa.text("'default_banner.jpg'"), nullable=True))
        batch_op.add_column(sa.Column('foto_perfil', mysql.VARCHAR(length=500), server_default=sa.text("'default.jpg'"), nullable=True))
        batch_op.add_column(sa.Column('provider', mysql.VARCHAR(length=50), server_default=sa.text("'local'"), nullable=True))
        batch_op.add_column(sa.Column('descripcion', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)

    op.create_table('mensaje',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amigo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contenido', mysql.TEXT(), nullable=False),
    sa.Column('fecha', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('leido', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['amigo_id'], ['usuario.id'], name='mensaje_ibfk_2'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='mensaje_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('amigo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amigo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.ENUM('pendiente', 'aceptado', 'rechazado'), server_default=sa.text("'pendiente'"), nullable=True),
    sa.ForeignKeyConstraint(['amigo_id'], ['usuario.id'], name='amigo_ibfk_2'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='amigo_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
