"""Añadir campos de edad y centro educativo a Usuario

Revision ID: c0e9e19d96a5
Revises: 703a892c3a0d
Create Date: 2024-12-12 06:15:44.009933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e9e19d96a5'
down_revision = '703a892c3a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('centro_educativo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('centro_educativo')
        batch_op.drop_column('edad')

    # ### end Alembic commands ###
